sudo: required
services:
  - docker

before_install:
  - docker build -t prathamesh99/react-test2 -f ./client/Dockerfile.dev ./client

script:
  - docker run prathamesh99/react-test2 npm test -- --coverage

after_success:
  - docker build -t prathamesh99/multi-client2 ./client
  - docker build -t prathamesh99/multi-nginx2 ./nginx
  - docker build -t prathamesh99/multi-server2 ./server
  - docker build -t prathamesh99/multi-worker2 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push prathamesh99/multi-client2
  - docker push prathamesh99/multi-nginx2
  - docker push prathamesh99/multi-server2
  - docker push prathamesh99/multi-worker2

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-1-306476627547
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
